# Generated by Django 3.1.3 on 2024-05-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0011_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='Description',
            field=models.TextField(default=''),
        ),
    ]
